### ISSUE TITLE
Improve detection of target Slack message

### ISSUE THREAD

**Issue by florimondmanca** [DataDog/slapr#5]
**Problem**

Currently the target Slack message (where the action will add emojis) is obtained as the first message that contains the following string:

```
👀 <PR_URL>
```

This allows us to match this kind of messages:

```
Need 👀 <PR_URL>
```

But this would fail on the many variations we use in the wild:

```
Can I have some 👀 on this one? <PR_URL>
Need 👀/✅ <PR_URL>
Can I get a review on this PR? <PR_URL>
```

**Suggested solution**

Use a machine learning approach: train a classifier to recognize messages where the author asks for a review on a pull request.

(Using ML/DL here fits the problem quite well since there are many variations around how people ask for review, and pattern-matching isn't enough to detect them all.)

**Alternatives**

- Use an arbitrary magic string that users have to add to , e.g. `rev <PR_URL>`.

This isn't great UX, and isn't very newcomer-friendly. (People coming by the Slack channel occasionally that aren't not familiar with the tool wouldn't know that they can have automatic emojis by adding the magic string.)

**Comment by AlexandreYang** [comment]
We now match the first URL, which seems to work fine. So, this seems not an issue anymore.

**Comment by AlexandreYang** [comment]
Feel free to reopen the issue if needed.
